package com.docarchitect.core.util;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/**
 * Utility class for generating deterministic IDs.
 *
 * <p>Uses SHA-256 hashing to generate consistent, collision-resistant IDs
 * from input strings.
 */
public final class IdGenerator {

    private IdGenerator() {
        // Utility class
    }

    /**
     * Generates a deterministic ID from input components.
     *
     * <p>The ID is generated by:
     * <ol>
     *   <li>Concatenating all input components with a delimiter</li>
     *   <li>Computing SHA-256 hash of the concatenated string</li>
     *   <li>Taking first 16 characters of the hex representation</li>
     * </ol>
     *
     * <p>Example:
     * <pre>{@code
     * String id = IdGenerator.generate("user-service", "v1.0.0");
     * // Returns: "a1b2c3d4e5f6g7h8"
     * }</pre>
     *
     * @param components input components to generate ID from
     * @return deterministic ID (16 characters)
     */
    public static String generate(String... components) {
        if (components == null || components.length == 0) {
            throw new IllegalArgumentException("At least one component required");
        }

        String input = String.join("|", components);
        return generateFromString(input);
    }

    /**
     * Generates a deterministic ID from a single string.
     *
     * @param input input string
     * @return deterministic ID (16 characters)
     */
    public static String generateFromString(String input) {
        if (input == null || input.isBlank()) {
            throw new IllegalArgumentException("Input must not be null or blank");
        }

        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(input.getBytes(StandardCharsets.UTF_8));
            String hexHash = HexFormat.of().formatHex(hash);
            return hexHash.substring(0, 16);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 algorithm not available", e);
        }
    }

    /**
     * Generates a full SHA-256 hash as hex string.
     *
     * @param input input string
     * @return full SHA-256 hash (64 characters)
     */
    public static String generateFullHash(String input) {
        if (input == null || input.isBlank()) {
            throw new IllegalArgumentException("Input must not be null or blank");
        }

        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(input.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hash);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 algorithm not available", e);
        }
    }
}
